### ISSUE TITLE
truss example missing bar labels ...

### ISSUE THREAD

**Issue by goessner** [goessner/g2#27]
The bar labels are missing with last truss example in g2.mec documentation.

**Comment by klawr** [comment]
The bar-examples were completely out of date... Fixed that.
Since they depended heavily on the old `dx`, `dy` notation, I allowed myself to add
examples how one could add a "parser" themself.

[Truss](https://github.com/goessner/g2/wiki/g2.mec)
[Truss with labels](https://github.com/goessner/g2/wiki/g2.mec#truss-example-with-labels)
