### ISSUE TITLE
Microsoft Edge not supported

### ISSUE THREAD

**Issue by jauhl** [goessner/g2#29]
Using the concatenated and minified version of g2 (including g2.chart), [g2.js]( https://github.com/goessner/g2/blob/master/src/g2.js) leads to errors in Microsoft Edge 42.17134.1.0, Microsoft EdgeHTML 17.17134.

It seems that Edge does not fully support [object spreading]( https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators/Spread_syntax), which is utilized often in g2.chart. 

Since mecEdit will be available as a UWP PWA in the future, it is highly desired and a requirement, that Edge is fully supported.

Maybe implement Object.apply() instead, like here [g2_apply.js](https://github.com/jauhl/mecEdit/blob/master/scripts/g2_apply.js). Note that this renders mecEdit without errors in Edge but is otherwise completely untested!

**Comment by goessner** [comment]
yes ... I agree. I also stumbled yesterday over that bug and intended to raise an issue also,

But there is no need for a new `Object` method, as `Object.assign` works identically to the alternate spread syntax.

See [this link](https://medium.com/dailyjs/goodbye-electron-hello-desktop-pwas-f316b8f39882) for a recent discussion of PWA's.

**Comment by klawr** [comment]
Should be polyfilled for Edge now.
If any issues occur please let me know.

**Comment by goessner** [comment]
For example in line 82 ...
```js
 g.beg(Object.assign({}, {x:this.x,y:this.y,lw:1}, this.defaults.style,this.style));
```
there is no need to have that empty object in the beginning, as the the second one can be modified as destination, as in
```js
 g.beg(Object.assign({x:this.x,y:this.y,lw:1}, this.defaults.style,this.style));
```
This should be less memory intensive and more performant.

**Comment by klawr** [comment]
I actually do think the difference can't be measured, or the JIT-Compiler would optimize this part anyway.
Anyway i changed this in 6a68bc320694605e6fbf56b51e1ed5c03c41f7d9

**Comment by jauhl** [comment]
Thanks, works now.

Although there is still some spreading going on in `g2.core.js` (e.g. [here]( https://github.com/goessner/g2/blob/ccd46c79444ccda52087dc7fb07dbba8613a194a/src/g2.core.js#L473) or [here](https://github.com/goessner/g2/blob/ccd46c79444ccda52087dc7fb07dbba8613a194a/src/g2.core.js#L882)), it doesn’t seem to be a problem for mecEdit for now. 

Maybe you can still get rid of those too, in the future.

**Comment by klawr** [comment]
This should be no problem.
In line [473](https://github.com/goessner/g2/blob/ccd46c79444ccda52087dc7fb07dbba8613a194a/src/g2.core.js#L473) a [rest parameter](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Functions/rest_parameter) is used, which looks like a spread-operator, but is none.
The [others](https://github.com/goessner/g2/blob/ccd46c79444ccda52087dc7fb07dbba8613a194a/src/g2.core.js#L882) are [supported in Edge](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility), since they are function-calls and not object-literals.

Let me know in case I missed one.
